name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Deploying PRODUCTION..."
            cd /var/www/managetgt
            git fetch origin
            git reset --hard origin/main
            npm install
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            pm2 restart managetgt

            